name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to v3 for Node.js 16 support

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Updated to v3 for Node.js 16 support
        with:
          node-version: "16" # Specifying Node.js version 16

      - name: Replace Secrets in JS
        run: |
          sed -i 's|YOUR_GOOGLE_API_KEY|'${{ secrets.API_KEY }}'|g' js/backup_drive.js
          sed -i 's|YOUR_GOOGLE_CLIENT_ID|'${{ secrets.CLIENT_ID }}'|g' js/backup_drive.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
