- name: Replace Secrets in JS
  run: |
    sed -i '' "s/YOUR_GOOGLE_CLIENT_ID/${{ secrets.CLIENT_ID }}/g" ./js/backup_drive.js || cat ./js/backup_drive.js
    sed -i '' "s/YOUR_GOOGLE_API_KEY/${{ secrets.API_KEY }}/g" ./js/backup_drive.js || cat ./js/backup_drive.js
